### ISSUE TITLE
Adding "maintainers" label to images

### ISSUE THREAD

**Issue by ppatierno** [jboss-container-images/amqstreams-1-openshift-image#198]
One of the CVP optional checks is failing due to the missing "maintainers" label on the images.
We should add that label to all the image descriptor files in the `labels` section as follow:

```yaml
labels:
  - name: "maintainer"
    value: "AMQ Streams Engineering <amq-streams-dev@redhat.com>"
```
