### ISSUE TITLE
Add platform specific "x86 64" build container information

### ISSUE THREAD

**Issue by ppatierno** [jboss-container-images/amqstreams-1-openshift-image#199]
AMQ Streams images are built only for the "x86 64" architecture.
We should reflect this into the image descriptor files in the `osbs.configuration.container` section like this:

```yaml
osbs:
  extra_dir: dist-git-files
  configuration:
    container:
      compose:
        pulp_repos: true
      platforms:
        only:
        - x86_64
  repository:
    name: containers/amqstreams-bridge
    branch: amqstreams-1.5-rhel-7
```
