### ISSUE TITLE
Missing s390x supported architecture in the CSV

### ISSUE THREAD

**Issue by ppatierno** [jboss-container-images/amqstreams-1-openshift-image#346]
The current CSV (AMQ Streams 2.1.0) is missing the label related to the support for s390x platform:

```yaml
labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/os.linux: supported
```

It should be added here https://github.com/jboss-container-images/amqstreams-1-openshift-image/blob/amqstreams21-dev/operator-metadata/manifests/bundle.clusterserviceversion.yaml#L385
