### ISSUE TITLE
Reinstall timezone data so that users can change the timezone of the logs

### ISSUE THREAD

**Issue by ppatierno** [jboss-container-images/amqstreams-1-openshift-image#388]
We have to reinstall the `tzdata` package in the Kafka images only because of the Kafka Exporter tool.
It was already done upstream via [PR#8178](https://github.com/strimzi/strimzi-kafka-operator/pull/8178).
The only problem I see when using the cekit tool and the image descriptor is that it seems not supporting the `reinstall` command.
I mean having something like this

```yaml
packages:
  manager: microdnf
  install:
    - unzip
    - tar
    - rsync
    - shadow-utils # groupadd
    - gzip
    - kafka_exporter
```

generate a shell command in the Dockerfile like this:

```shell
microdnf install ....
```

While we need a `reinstall` command. From official documentation it seems there is no  such a support https://docs.cekit.io/en/latest/descriptor/image.html#packages-to-install
